### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by rocket1106** [perceptron8/pinky.ext#14]
it has stopped working with the xmas preview on the tso test server....???

is this a normal as it was working on the 29/10 then stopped on 30/10..?

**Comment by perceptron8** [comment]
Hi! It's because of some optimalizations in Pinky, not because of Christmas.

Since version 0.2.0, Pinky redirects only http://static.cdn.ubi.com/0018/live/... urls. Previously also http://static.cdn.ubi.com/0018/prestaging/... was redirected.

Should I include "prestaging" in 0.2.1 again?

**Comment by rocket1106** [comment]
Seems that way as on the test svr, nothing is showing up where it was working brilliantly before.....

std svr no problems even during current event...saves a huge amount of time :)) Kudos

**Comment by perceptron8** [comment]
Please, wait for 0.2.1. I'll try to release it within one week from now. Be patient :)
