### ISSUE TITLE
Not working in FF 49.0.2

### ISSUE THREAD

**Issue by horacis** [perceptron8/pinky.ext#15]
I've got an error:
![settlersonlinepinkyerror](https://cloud.githubusercontent.com/assets/23548718/20421726/18a1d1b4-ad66-11e6-87a6-47a9f25e0e13.jpg)

**Comment by perceptron8** [comment]
Please let me know if you have Electrolysis (e10s) enabled. See https://wiki.mozilla.org/Electrolysis#Firefox_Release for details.

**Comment by horacis** [comment]
I'm very sorry.
I didn't notice that e10s was not enabled. It's working fine.

Thank you and best regards

**Comment by perceptron8** [comment]
Don't be sorry! :) I was convinced that e10s is going to be enabled by default since 48. I'll include some warning in README soon. Thanks for feedback & best regards!
