### ISSUE TITLE
Test server + i18n

### ISSUE THREAD

**Issue by goofas** [perceptron8/pinky.ext#16]
witam jest rozszerzenie, które spolszcza grę niestety aby je zainstalować trzeba je opublikować w sklepie chrome czy jest szansa abyś dodał je również ? http://userscripts-mirror.org/scripts/show/102221

**Comment by perceptron8** [comment]
Hej!

Mogę pomóc w stworzeniu odpowiedniego rozszerzenia. Przejrzałem podlinkowany kod. Poniżej kilka wskazówek.

1. Greasemonkey warto zastąpić czymś bezpieczniejszym i bezpośrednio dostępnym: https://developer.chrome.com/extensions/content_scripts
2. Nie warto zaszywać w kodzie rozszerzenia, które ma być neutralne językowo, stałych w rodzaju "zmień język" czy "ustaw kraj". Z tego samego powodu nie warto traktować języka polskiego jako domyślnego (jeśli dobrze rozumiem, jest nim przy braku API z Greasemonkey). Bardziej rozsądne będzie wykorzystanie metody https://developer.chrome.com/extensions/i18n#method-getAcceptLanguages.

Życzę powodzenia i czekam na informacje o postępach :-)

**Comment by perceptron8** [comment]
Ze względu na wzmiankę w #18, postanowiłem stworzyć coś swojego. Rozszerzenie ustawia język gry na podstawie języka interfejsu użytkownika przeglądarki (uwaga: czasami dopasowanie nie jest możliwe). Mam nadzieję, że komuś się to do czegoś przyda.

https://github.com/perceptron8/babel.ext
