### ISSUE TITLE
Firefox Issue

### ISSUE THREAD

**Issue by WatchDog007** [perceptron8/pinky.ext#17]
After activating Pinky in Firefox i went to a scenario, which is working great in Opera and Chrome...
But in Firefox i receive this message after entering the scenario:

File loading failed! Please check your network connection, clean your browser cache or try again later.

I cleaned my cache more then once, closed browser as well, but still same issue.
Any idea?
BTW... great job, it makes it fun again to play scenarios which i was avoiding for a long time...

**Comment by perceptron8** [comment]
1. Are no-scenario collectibles being replaced in FF? It's more likely all or nothing.
2. Do you have Electrolysis enabled? See https://github.com/perceptron8/pinky.ext#usage

**Comment by WatchDog007** [comment]
1. good question ^^ can't check yet, just collected all items on my island with Opera, will check in 9h
2. using FF 50.0.2, on about:support i found 
Multi-process staged rollout	1.5	true	e10srollout@mozilla.org

found in abpout:config 
browser.tabs.remote.autostart2 on true. 
browser.tabs.remote.autostart still on false... set it on true

cleaned all and everything by closing FF (cache, cookies, history...), restart it, tried, fail
still same issue

**Comment by perceptron8** [comment]
If it's still the same... Could you use about:support -> [Copy text to clipboard] and paste "Multiprocess Windows" entry? Here's mine:
> Multiprocess Windows: 1/1 (Enabled by user)

**Comment by WatchDog007** [comment]
browser.tabs.remote.force-enable
solved the issue, which i really don't want to try before , but finally ^^ it works fine
and BTW FF sucks ^^ get rid of it guys, it was fine for a long time, but they messed it up.

@perceptron8 what do u think about Vivaldi, the new Browser of Operas Ex-Founder?

**Comment by perceptron8** [comment]
That's good! :-) I hope that Pinky will work fine from now on!

I don't know Vivaldi, sorry.

Thank's for feedback! :-)

**Comment by perceptron8** [comment]
Duplicate of #15

**Comment by WatchDog007** [comment]
btw...
featureed your tool on [http://www.zwergenstadt.com/](url)

**Comment by WatchDog007** [comment]
btw featured your tool on
[http://www.zwergenstadt.com](http://www.zwergenstadt.com)
