### ISSUE TITLE
Bez włączania e10s ?

### ISSUE THREAD

**Issue by tOOmki** [perceptron8/pinky.ext#18]
Dało by radę zrobić dodatek bez wykorzystywania e10s ?
Jak włączę e10s to mam problem z jedna stroną (system Domoticz).

ps. Zgłosiłem już im to na forum i ciekawe czy dadzą radę to naprawić.

**Comment by perceptron8** [comment]
Dodatek w żaden sposób nie wykorzystuje e10s.

Włączenie e10s w FF jakimś cudem sprawia, że Flash reaguje poprawnie na przekierowywanie żądań. Zobacz https://bugzilla.mozilla.org/show_bug.cgi?id=1114891, https://bugzilla.mozilla.org/show_bug.cgi?id=1171407. Pierwszy błąd zgłosiłem ponad 2 lata temu, do dziś nawet go nie potwierdzono (status: new). Oba mogą mieć związek z https://bugbase.adobe.com/index.cfm?event=bug&id=3711074. Wygląda na to, że obsługa Flasha i single-process średnio kogokolwiek w Mozilli obchodzi.

**Comment by tOOmki** [comment]
Re: [perceptron8/pinky.ext] Bez w³¹czania e10s ? (#18)



Witam!

W liście datowanym 31 grudnia 2016 (09:45:47) napisano:





Dodatek w żaden sposób nie wykorzystuje e10s.
Włączenie e10s w FF jakimś cudem sprawia, że Flash reaguje poprawnie na przekierowywanie żądań. Zobacz https://bugzilla.mozilla.org/show_bug.cgi?id=1114891, https://bugzilla.mozilla.org/show_bug.cgi?id=1171407. Pierwszy błąd zgłosiłem ponad 2 lata temu, do dziś nawet go nie potwierdzono (status: new). Oba mogą mieć związek z https://bugbase.adobe.com/index.cfm?event=bug&id=3711074. Wygląda na to, że obsługa Flasha i single-process średnio kogokolwiek w Mozilli obchodzi.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Witam,

A jak wpadłeś na to że trzeba włączyć e10s żeby przekierowania poprawnie działały ?
Bo w  sumie po zainstalowaniu dodatku ale bez włączenie e10s, grafiki z przedmiotami znikają oraz dostaje błąd o błędnym ładowaniu danych.
Nie da się użyć innego przekierowania lub ewentualnie przerobić na skrypt pod greasemonkey ?
Pod greasemonkey używam skryptu zmieniającego język na polski, bo gram od ponad 6 lat na niemieckim serwerze.

-- 
Pozdrowienia,
 Tomek
 toomki@o2.pl

 Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne.
 Lasy będą Ci wdzięczne :]

**Comment by perceptron8** [comment]
Co jakiś czas sprawdzałem nowe wersje FF, żeby móc zgłosić ew. naprawienie błędu. W pewnym momencie okazało się, że w którejś z nich problem nie występuje. Zgłosiłem. Okazało się, że działa, ale nie zawsze. Niedługo potem stało się jasne, że chodzi o e10s.

Nie da się użyć innego przekierowania, greasemonkey nie ma tu zastosowania - nawet gdyby miało, lepszy byłby content script (sprawdź #16). Żądania wychodzą bezpośrednio z Flasha. Nie da się ich zmodyfikować z poziomu przeglądarki inaczej niż poprzez https://developer.chrome.com/extensions/webRequest (ew. jakiś wcześniejszy odpowiednik).

Przy okazji: mogę zapytać, czemu niemiecki serwer? To już drugie zgłoszenie, w którym wspomniano o skrypcie do zmiany języka. W Pinkym czegoś takiego nie planuję (wymagałoby to dodatkowych uprawnień), ale nie wykluczam stworzenia nowego rozszerzenia. W razie czego pisz, proszę, w #16.

**Comment by tOOmki** [comment]
Re: [perceptron8/pinky.ext] Bez w³¹czania e10s ? (#18)



Witam!

W liście datowanym 31 grudnia 2016 (10:44:20) napisano:





Co jakiś czas sprawdzałem nowe wersje FF, żeby móc zgłosić ew. naprawienie błędu. W pewnym momencie okazało się, że w którejś z nich problem nie występuje. Zgłosiłem. Okazało się, że działa, ale nie zawsze. Niedługo potem stało się jasne, że chodzi o e10s.
Nie da się użyć innego przekierowania, greasemonkey nie ma tu zastosowania - nawet gdyby miało, lepszy byłby content script (sprawdź #16). Żądania wychodzą bezpośrednio z Flasha. Nie da się ich zmodyfikować z poziomu przeglądarki inaczej niż poprzez https://developer.chrome.com/extensions/webRequest (ew. jakiś wcześniejszy odpowiednik).
Przy okazji: mogę zapytać, czemu niemiecki serwer? To już drugie zgłoszenie, w którym wspomniano o skrypcie do zmiany języka. W Pinkym czegoś takiego nie planuję (wymagałoby to dodatkowych uprawnień), ale nie wykluczam stworzenia nowego rozszerzenia. W razie czego pisz, proszę, w #16.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Niemiecki serwer, dlatego że był jako pierwszy, potem chyba po ponad roku pojawił się angielski i inne języki w tym i polski.
Żal mi było stracić ponad rok gry. Pisałem do supportu o przeniesienie konta z DE na PL - nie da rady.

-- 
Pozdrowienia,
 Tomek
 toomki@o2.pl

 Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne.
 Lasy będą Ci wdzięczne :]

**Comment by perceptron8** [comment]
Rozumiem. Zasubskrybuj #16, jeśli chcesz. W razie, gdyby coś w temacie ew. nowej wtyczki się zmieniło, dodam tam komentarz.

**Comment by tOOmki** [comment]
Re: [perceptron8/pinky.ext] Bez w³¹czania e10s ? (#18)



Witam!

W liście datowanym 31 grudnia 2016 (10:44:20) napisano:





Co jakiś czas sprawdzałem nowe wersje FF, żeby móc zgłosić ew. naprawienie błędu. W pewnym momencie okazało się, że w którejś z nich problem nie występuje. Zgłosiłem. Okazało się, że działa, ale nie zawsze. Niedługo potem stało się jasne, że chodzi o e10s.
Nie da się użyć innego przekierowania, greasemonkey nie ma tu zastosowania - nawet gdyby miało, lepszy byłby content script (sprawdź #16). Żądania wychodzą bezpośrednio z Flasha. Nie da się ich zmodyfikować z poziomu przeglądarki inaczej niż poprzez https://developer.chrome.com/extensions/webRequest (ew. jakiś wcześniejszy odpowiednik).
Przy okazji: mogę zapytać, czemu niemiecki serwer? To już drugie zgłoszenie, w którym wspomniano o skrypcie do zmiany języka. W Pinkym czegoś takiego nie planuję (wymagałoby to dodatkowych uprawnień), ale nie wykluczam stworzenia nowego rozszerzenia. W razie czego pisz, proszę, w #16.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Ja za cienki jest na samodzielne pisanie kodu, czasami udaje mi się przerobić proste skrypty lub naprawić jakąś pierdółkę.
Nie te studia skończyłem :] na mechanice był tylko C++.

-- 
Pozdrowienia,
 Tomek
 toomki@o2.pl

 Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne.
 Lasy będą Ci wdzięczne :]
