### ISSUE TITLE
Mouse click on buildings not working

### ISSUE THREAD

**Issue by Gavona** [perceptron8/pinky.ext#21]
I use Pinky web extension in Chrome
I click on a building and nothing happens.  clicking elsewhere works fine.  I can open the economy tool, see a list of buildings, open the building window that way.
No problem if I exit pinky and just load game in Chrome.

I love pinky so really hope I can help you to track down the issue.

**Comment by perceptron8** [comment]
I'll check this in about 4-6 hours.

**Comment by Gavona** [comment]
http://www.thesettlersonline.com/en/homepage
Newfoundland

Perhaps I should have said that this issue started in the past week or two.  I think perhaps it comes after I have been playing for a while.  I tried restarting, clearing cache etc but does not help..... 

Looking for more info for you and discovered that I didn't have the latest version of chrome. 
On PC I had Version 56.0.2924.87 (64-bit)  and on laptop I had a slightly earlier version.
Both are now upgraded to Version 57.0.2987.110 (64-bit)

Since upgrading Chrome in the last half hour I do not have the problem on either machine.  Could that have been the issue?  I will let you know if the problem comes back.

Thanks
Gavona

**Comment by Gavona** [comment]
oops I closed the issue by mistake

**Comment by perceptron8** [comment]
It could be something with Chrome, Flash or TSO itself. Pinky hasn't been modified since January. If problem comes back, please let me know.

Thanks for help!
