### ISSUE TITLE
Crashing on Firefox?

### ISSUE THREAD

**Issue by jjarh** [perceptron8/pinky.ext#23]
Hi, 
I'm using pinky for firefox and it keeps crashing and slowing down browser. Chat keeps crashing and it times out all the time causing flash to crash. If i remove pinky then it works fine. I also have pinky on chrome and that seems to work great. please fix. thx

**Comment by perceptron8** [comment]
Hi!

I'm sure it's Firefox's bug. Why? As you can see Chrome is fine. Opera is fine too. Are previous FF versions crashing when Pinky is installed?

Please, check permissions in [manifest.json)](https://github.com/perceptron8/pinky.ext/blob/master/manifest.json). Chat requests shouldn't be intercepted at all! I believe that you have some problems with Firefox when Pinky is installed, but they are probably related to [Electrolysis](https://wiki.mozilla.org/Electrolysis). Maybe you should fill an issue at https://bugzilla.mozilla.org/ (search for similar bugs first!).

I'd like to reproduce this error too as I'm curious about what causes crashes. Maybe I could help with bugzilla then. Please, provide me some details about your browser (exact version), operating system and flash plugin.
