### ISSUE TITLE
Test Server: URL Change to HTTPS

### ISSUE THREAD

**Issue by Bomber686** [perceptron8/pinky.ext#24]
Hi,

Thanks for pinky, awesome tool.  I've just been on the test server and settlers online is testing a new https protocol.  This stops pinky from working.  Not sure if you can workaround this issue but please investigate.

**Comment by perceptron8** [comment]
I'll check it out, thanks!

**Comment by perceptron8** [comment]
They use https://ubistatic-a.akamaihd.net/ for now. I'm going to wait some time to see if they are going to keep it.

**Comment by perceptron8** [comment]
Closed in fcde8706f86258a98e6049e9b37b154cae49ed77. @Bomber686, thanks again! :-)
