### ISSUE TITLE
Issue on Firefox 52.2.0 esr

### ISSUE THREAD

**Issue by williamvun** [perceptron8/pinky.ext#25]
Didn't work on latest Firefox 52.2.0. Please update it.

**Comment by perceptron8** [comment]
Did it worked before? Is it fresh install? Do you have [Electrolysis](https://wiki.mozilla.org/Electrolysis#Firefox_Release) enabled?

I can't check 52.2.0, but on 53.0.3 it works like charm.

**Comment by perceptron8** [comment]
Confirmed. This is https://bugzilla.mozilla.org/show_bug.cgi?id=1311815 backported to 52. Please follow #26. Thanks for submission!
