### ISSUE TITLE
Pinky stopped working after FF 54.0 Update

### ISSUE THREAD

**Issue by Raubhautz** [perceptron8/pinky.ext#26]
Immediately following the 54.0 Firefox update, Pinky stopped working. I cleared cache, restarted the browser - no avail; removed Pinky, reinstalled Pinky, cleared cache - no avail; Verified Electrolosis is enabled.

I note that the comment in the description of Pinky now shows support for FF 57.0... Is this to mean we have to wait until then (~November) fore Pinky to work in FF again?

**Comment by perceptron8** [comment]
Pinky requires 48+. There was no new Pinky version since February. This 57+ is some kind of FF fresh-and-great-technology-self-promotion. You won't have to wait, don't worry.

It may be that this is FF problem. If so, I can't help you. It is possible however, that something changed in TSO itself. I'll try to help you. What region do you choose to play?

**Comment by Raubhautz** [comment]
Hi, 

     Thank you for your generosity in this issue. I'm on the Zeus (North American Server 1); I also have an account on German Server #9 (Schneefeuer). Pinky worked on both this morning, then I updated FF... no longer works on either server. :( I have noticed that Pinky continues to work for both servers using Chrome and Opera browsers. It appears to be directly related to the FF update to 54.0. Any and all suggestions would be welcome.

Sincerely,

 

 

Phil
 

 

-----Original Message-----

**Comment by perceptron8** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1311815... Looks like they "FIXED" something again... I'm tired.

I'll investigate more.

**Comment by perceptron8** [comment]
I could make Pinky work on FF again by adding all possible origin hosts for all regions near [manifest.json#L33](https://github.com/perceptron8/pinky.ext/blob/0f695736d2c1c6a1117b023fe188099b45a6c64e/manifest.json#L33), but that's just ridiculous.

I suppose most of web-exts authors will simply switch to "<all_urls>". This is how secure FF44 is going to be. Yes, I'm happy too.

I need some time to think about this.

**Comment by Raubhautz** [comment]
Yes, that was an interesting thread... not sure how much that is suppose to help security, but there it is. That is great if you get around to making it compatible with FF44+, meanwhile I reinstalled FF43 and will stay there until absolutely necessary.

 

 

Phil
 

 

-----Original Message-----

**Comment by perceptron8** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1311815#c35

**Comment by pusher99** [comment]
hi there,
will u get pinky running again?
can i help to solve the problem?

martin

**Comment by perceptron8** [comment]
Version 0.2.4 has been submitted for review. Up to FF53, host permissions are completely ignored. In FF54, checks are too restrictive. I really hope this is temporary.

**Comment by perceptron8** [comment]
After a long battle... Please, go for 0.2.5! :)

**Comment by PanicMan** [comment]
Still not working with FF54. Get every time I start DSO the message that an resource cannot be loaded and I have to clean the cache or try again later. Did it already several times and restarted. nothing helps. Checked the changes, except of the version number it seems there is nothing else changed... ^^

**Comment by perceptron8** [comment]
@PanicMan There is something that changed. Permissions. See [manifest.json#L33](https://github.com/perceptron8/pinky.ext/blob/5abe6de6bf485e6d99191e7ed6fd2c3e9dd72643/manifest.json#L33) - note that this change is for firefox branch only.

Are you sure that Electrolysis wasn't disabled during FF upgrade? Please go check _Help -> Troubleshooting Information_ and let me know if _Multiprocess Windows_ option is enabled.

**Comment by Pinky-Brain** [comment]
Hi perceptron8,
I have the same problem.

The settings are:
-->about:support
Fenster mit mehreren Prozessen 	0/1 (deaktiviert)
-->about:config 
browser.tabs.remote.autostart;false
browser.tabs.remote.autostart.2;false
browser.tabs.remote.force-enable;false

Thanks!

FF 54.0 (32-bit)
Pinky 0.2.5.(20.06.2017)

**Comment by perceptron8** [comment]
@Pinky-Brain As you can see, Electrolysis is disabled. To enable it, follow the instructions from https://wiki.mozilla.org/Electrolysis#Force_Enable. Note that you may break some other extensions at the same time.

**Comment by Pinky-Brain** [comment]
Oh shi... I'm PinkyWithOutBrain ... If you can read you are in advantage!
Sorry, but I confounded enable and disable ...
Now it works very well!

Thanks for your help!
