### ISSUE TITLE
Firefox & Pinky won't load collectables

### ISSUE THREAD

**Issue by sknortsch** [perceptron8/pinky.ext#28]
Hi,

it seems that firefox isn't loading the collectables with pinky activated. I get "File loading failed! Please check your network connection, clean your browser cache or try again later."

Is it possible that this is a pinky-related problem or is it firefox itself?

With chrome everything works fine.

**Comment by perceptron8** [comment]
Duplicate od #15. See #17 also. Please enable Electrolysis and let me know if the problem persist.

**Comment by sknortsch** [comment]
Thanks for that fast response. I did what was said there, but the problem still exists.
I also read about the possibility to solve it by enabling "browser.tabs.remote.force" like another user did, but I cannot find that entry in my about:config.

**Comment by perceptron8** [comment]
They changed this magic "super.unstable.entry.name" 2 or 3 times (this is how they maintain backward compatibility at Mozilla)...

I believe that, as of today, you have to create new boolean pref called **browser.tabs.remote.force-enable** and set it to `true`. Check at https://wiki.mozilla.org/Electrolysis#Force_Enable to be sure.

**Comment by sknortsch** [comment]
Thanks a lot, with this new boolean it's working all fine! And thanks again for responding that fast :-)

**Comment by perceptron8** [comment]
Glad to hear that! You are welcome! :-)
