### ISSUE TITLE
PINKY doesn't work after fake-event

### ISSUE THREAD

**Issue by bordsteinlatscher** [perceptron8/pinky.ext#29]
PINKY doesn't work after the fake-event "Black Knight/SCHWARZER  RITTER" (2017.july.24th  15:30 h). It doesn't replace the icons with pinky ones. Tested on Google Chrome and Win 10. Bluebyte has changed something

**Comment by ajkpark** [comment]
The same configuration ... The Chrom browser wnated to agree some Flash update, after that is not working ...  :*(

**Comment by bordsteinlatscher** [comment]
PINKY even doesn't work in adventures. 
http://images.devs-on.net/Image/agnvRfzIdrjEbNIH-Bereich.png

**Comment by bordsteinlatscher** [comment]
# #

**Comment by bordsteinlatscher** [comment]
Sorry my mistake

**Comment by bordsteinlatscher** [comment]
@ajkpark:   
Yes, in some cases Chrome requires a flash update.
That is strange

**Comment by Raubhautz** [comment]
Same issue: Pinky no longer works following that Fake Event. Tried in FF, Chrome and Opera and both in game and adventures, no more. :(

**Comment by Raubhautz** [comment]
Peeps, Chrome occasionally resets its default options on you, which is why you may get that bogus Flash is out of date warning. Go back in settings and approve Flash to run for TSO (ore whatever you desire).

**Comment by perceptron8** [comment]
Looks like they switched from http:// to https://. I'll release a new version within 1 hour. Thanks for report!

**Comment by Raubhautz** [comment]
Thank you for not only an awesome product and a reply to a question, but a prompt response and update.

 

 

Phil
 

 

-----Original Message-----

**Comment by bordsteinlatscher** [comment]
Yes, PINKY is a great help. I don't wanna live and play DSO /TSO without PINKY. Thanks a lot, perceptron8!

**Comment by perceptron8** [comment]
Chrome: published, ready.
Firefox: approved, available for download.
Opera: awaiting moderation.

**Comment by hapeen** [comment]
Sorry, but it doesn`t work at chrome and i dont know what to do.
I want miss ist, its a great little thing!
Please help!

**Comment by hapeen** [comment]
AAAAAAA, thanks, there ist it, great, thanks a lot!

**Comment by ajkpark** [comment]
No.1 ... THX !!!

**Comment by perceptron8** [comment]
https://forum.thesettlersonline.com/threads/35065-URL-change-HTTP-gt-HTTPS
One day after. Better late than never?

BTW. I'm still waiting for Opera moderators.

**Comment by perceptron8** [comment]
My mistake. I did not receive a notification, but here's the last one! :)

> Pinky v0.2.7 on Opera Current: Published.
> Jul 25, 2017 12:11:26 PM UTC

Thank you all for your patience!

**Comment by Raubhautz** [comment]
Was able to update Opera this morning! Thanks again for EVERYTHING!

 

 

Phil
 

 

-----Original Message-----
