### ISSUE TITLE
Firefox trouble

### ISSUE THREAD

**Issue by skipper118** [perceptron8/pinky.ext#30]
![firefox-trouble](https://user-images.githubusercontent.com/7859819/28528800-0c994180-708f-11e7-9ffa-9d2c3a3a3b79.png)
any idea what I'm making wrong ?

**Comment by perceptron8** [comment]
Yes. Electrolysis may be disabled. See #15. There is a new problem also, so please wait until #29 is fixed.

**Comment by perceptron8** [comment]
#29 has been fixed. Please let me know if enabling Electrolysis helped.

**Comment by Tonbandsalat** [comment]
i do follow steps to re run pinky nice:
1.check if multiprozess window is enable or disable
about:support
2. to enable
about:config
search for string: browser.tabs.remote.autostart
right click in the list below  browser.tabs.remote.autostart
choose: new/boolean 
fill in:  browser.tabs.remote.force-enable
restart ur browser check with about:support if multiprozess windows is enable 
the settlers should be running fine now with pinky :100:

**Comment by perceptron8** [comment]
Please follow https://wiki.mozilla.org/Electrolysis#Firefox_Release. In other words: is E10s really enabled now?

**Comment by Tonbandsalat** [comment]
yes it works after i`d enable it.

**Comment by Tonbandsalat** [comment]
it is enable and pinky works perfect. :)

**Comment by perceptron8** [comment]
Did you restart FF? Did you clear cache?

**Comment by perceptron8** [comment]
Oh, ok. Good to know :)
Greets!
