### ISSUE TITLE
does not work in opera from today

### ISSUE THREAD

**Issue by IronHiide** [perceptron8/pinky.ext#31]
does not work in opera from today

**Comment by perceptron8** [comment]
Duplicate of #29. See https://github.com/perceptron8/pinky.ext/issues/29#issuecomment-317458682. From *add-on metadata control panel*:

> Pinky v0.2.7 was submitted. Awaiting moderation.

Please be patient. It's up to Opera reviewers now. Usually it takes about 24 hours.

**Comment by perceptron8** [comment]
> Pinky v0.2.7 on Opera Current: Published.
