### ISSUE TITLE
feedback and marking missing from friends isles

### ISSUE THREAD

**Issue by ciarabelle** [perceptron8/pinky.ext#34]
If i mark on my isle  - the collect jingles and disappears as normal.  But since last weeks Uplay login issues when i mark on a friends isle, there is no responding jingle, no mark of the collect.  The collect does turn pink. 
so far i have
removed and reinstalled pinky
cleared cache and of course -- restarted chrome several times. 
removed pinky - cleared cache and restarted chrome  — collects again start marking - 
as soon as i add pinky back - no more feedback or marking on friends isles
chrome Version 60.0.3112.113 (Official Build) (64-bit)
thanks in advance

**Comment by perceptron8** [comment]
Works for me. There is several seconds delay between clicking and getting feedback. Maybe that's what bothers you?

**Comment by ciarabelle** [comment]
no i've waited 5 min for feedback - nothing.... this started immediately after the uplay login issues last week.  normal lag is less than 30 btw. other friends do not have the issue but i am not able to pinpoint the cause.

**Comment by perceptron8** [comment]
I was able to reproduce this with and without Pinky. Could you please confirm the second case?

**Comment by ciarabelle** [comment]
it failed without pinky until i cleared the cache and restarted chrome.. then it started working again - i tested a few minutes only without pinky (what with it being difficult to find them without lol). i reinstalled pinky - it worked for maybe 10 minutes then failed again. i'm not sure why it stops working.  i tested on the test tso server  (https://www.tsotesting.com/en/play) - pinky was working there.  (which is running in a tab in the same browser.) I logged out of test and back in test today, still working. tested in standard game tab - no marking on friends isle still (fresh login this morning). ran flash update today and restarted browser. tested again - failed in standard game play on friends isle (waited over a min for response), still worked in test server on friends isle.

**Comment by perceptron8** [comment]
Remove Pinky, clear cache, restart Chrome. Check if bug still appears. I'll do the same.

**Comment by ciarabelle** [comment]
removed pinky
cleared cache
restarted
loaded standard game - no other tabs
(had a friend leave a collie i found there) even though i marked it during bug - its still unmarked
attempted to mark kettle
it glowed - thats it - waited 1 min - no feedback - no arrow.

Version 60.0.3112.113 (Official Build) (64-bit)
Automatic updates are turned on

**Comment by perceptron8** [comment]
Same here. As you can see, it has nothing to do with Pinky.
Looks like it's Chrome or TSO related problem.
What about Firefox?

**Comment by ciarabelle** [comment]
i was going to report it to gave devs but they it worked in test and it worked without pinky for a while.  test in firefox shows same error - glows but doesn't mark. Will email game devs - thanks.

**Comment by perceptron8** [comment]
You are welcome!
