### ISSUE TITLE
Collectibles from "Of Songs and Curses"

### ISSUE THREAD

**Issue by ofsongsandcurses** [perceptron8/pinky.ext#35]
Hello there,

I would appreciate it very much if you could add the collectibles from "Of Songs and Curses" (Excelsior venture) to your Pinky extension (10 Papierschnipsel and 1 Holzfälleraxt). It's very time consuming to find these without visual indication.

Thanks in advance!

**Comment by perceptron8** [comment]
Thanks for taking the time and letting me know about these 2 missing items!
Pinky v0.2.8 has been submitted and is awaiting moderation.

**Comment by ofsongsandcurses** [comment]
Works great, thank you
