### ISSUE TITLE
Event-collectibles

### ISSUE THREAD

**Issue by ChrSchultz** [perceptron8/pinky.ext#36]
Hello perceptron8
is it possible to you, to add the collectibles from Helloween-, Christmas, Eastern and perhaps Footbal-Event to the pinky-extension?
Thanks
ChrSchultz

**Comment by ChrSchultz** [comment]
closed, i have had a look into the code, and I've found all these collectibles..

**Comment by perceptron8** [comment]
Yep, they are all here. :)
