### ISSUE TITLE
Pinky is not showing..

### ISSUE THREAD

**Issue by javit123** [perceptron8/pinky.ext#37]
Hei, guys!
THank you a lot for such a good programm,  which is  helping a lot in game.
Just 2 things to tell- now in Settlers they are hiding items so close behind the buildings, that would be nice to make pinky icons a little-bit bigger, if possible. It was not like this before, just last 2-3 weeks.
And second- it is not showing pushcarts in the adventura explosive Nordic character.
[https://prnt.sc/ixuefk](url)
If possible, can you add those as well, please?
Wish you the luck in your life, and once again- thanks a lot from myself and my guildmates!
Regards, Vit

**Comment by perceptron8** [comment]
Ad 1. As for bigger icons, it's not possible. Game engine uses some constants loaded from encrypted configuration file to trim images. Size is irrelevant¹.

Ad 2. Unfortunately, link that you gave is broken (was that a screenshot?). Please provide a working one or use more standard naming. Did you mean "Raid of the Nords"? If so, it's here: http://settlersonlinewiki.eu/en/adventures/ventures/raid-of-the-nords/raid-of-the-nords-general-200-with-elite-soldiers/. Which one of the collectibles would you like so see in pink?

¹ In fact, [f9f7e2bacd84c76001820a3621bda5c6959d609d](https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/f9f7e2bacd84c76001820a3621bda5c6959d609d.png) is used as substitution for all collectibles - as you can see, every one of them ends up having original size.

**Comment by perceptron8** [comment]
@javit123 Closing for now. Feel free to comment if something is missing.

**Comment by comdar** [comment]
Po najnowszej aktualizacji Pinky przestał działać i nie można zainstalować ponownie. Lipa

**Comment by perceptron8** [comment]
@comdar Masz na myśli aktualizację Pinky'ego czy Settlersów? Zobacz #55. Twórcy gry postanowili zmniejszyć rozmiar plików. Nazwy plików, które są pochodną ich treści, zmieniły się, a to oznacza, że Pinky musi teraz przechwytywać inne żądania niż przed aktualizacją Settlersów. W związku z tym opublikowałem nową wersję (0.4.2). Po pierwsze uwzględnia ona nowe adresy kolekcji, po drugie - ze względu na zmiany w Chrome od wersji 72 - rozszerza listę uprawnień (aby przechwycić żądanie trzeba teraz mieć uprawnienia nie tylko do zasobu blokowanego, ale również do strony, z której pochodzi żądanie). Jakiej przeglądarki używasz i w której wersji? Która wersja Pinky'ego nie działa?
