### ISSUE TITLE
Besieged City

### ISSUE THREAD

**Issue by Cathjavelin** [perceptron8/pinky.ext#39]
There's a collectible showing on the map near the final camp but it doesn't exist.

**Comment by perceptron8** [comment]
What do you mean by collectible that is visible but doesn't exist?
Could you provide a screenshot?

**Comment by perceptron8** [comment]
I've just noticed that most of urls changed, but only on staging version.
Were you using https://www.tsotesting.com/ maybe?

**Comment by Cathjavelin** [comment]
No - using the normal site. There is a pink square showing on the adventure as if there is a collectible but it isn't one. I don't have a screen shot but if I do the addy again, I'll get one. I'm guessing it's a similar looking 'thing' on the map that's getting marked up.

**Comment by perceptron8** [comment]
> I'm guessing it's a similar looking 'thing' on the map that's getting marked up.

It's not possible. Pinky doesn't work this way. There's no image recognition involved. Pinky uses a list of known collectibles image urls.

> I don't have a screen shot but if I do the addy again, I'll get one.

Ok, I'll wait, thanks!

**Comment by perceptron8** [comment]
@Cathjavelin Just to let you know, recent problems with https://www.tsotesting.com/ has been resolved in #40, so you may be able to reproduce "Besieged City" using *prestaging* server if you like.
