### ISSUE TITLE
Unable to load extension

### ISSUE THREAD

**Issue by peter-milliken** [perceptron8/pinky.ext#41]
Just re-imaged my computer and went to reload Pinky. I'm getting an error message:

An Error Has Occurred 
Could not move extension directory into profile

I have been using it successfully in the past.

**Comment by perceptron8** [comment]
You may need to upgrade your web browser. Since v0.3.0, Pinky requires Chrome 65 / Firefox 60 / Opera 52. Please verify whatever are have installed and let me know.

It's also possible that you encountered some problem with file/directory permissions.

**Comment by perceptron8** [comment]
Most likely not Pinky related... See:
- https://bugs.chromium.org/p/chromium/issues/detail?id=363317
- https://productforums.google.com/forum/#!topic/chrome/Hfs-xpJ0PkM

**Comment by peter-milliken** [comment]
OK, it was caused by running Chrome in a Comodo Sandbox - the thing that threw me was I was able to install other extensions from the Google Store.
Thanks for a great extension, btw! :-)

**Comment by perceptron8** [comment]
Glad to hear that. You are welcome! :-)
