### ISSUE TITLE
All objects are no longer marked!

### ISSUE THREAD

**Issue by aestivo** [perceptron8/pinky.ext#44]
Hi,
Since today, all objects are no longer marked!
Thank you

**Comment by perceptron8** [comment]
In what region do you play?

**Comment by aestivo** [comment]
I play in France. Realm 1 (Terre d'ambre)

**Comment by perceptron8** [comment]
And what browser do you use?

**Comment by aestivo** [comment]
i use Chrome Browser (last version) only tons, leather and bag of cereals are not marked.

**Comment by perceptron8** [comment]
Ok, thanks! I use "Poland / Złota Góra" and "Staging / Prestaging" for ordinary tests. Today I'll check France servers too. I'll try to update Pinky in about 6-8 hours.

**Comment by perceptron8** [comment]
@aestivo Could you please check if everything is ok with Pinky v0.4.0? It should update itself soon, but you may force this right now by going to chrome://extensions/, enabling Developer Mode (upper right corner) and clicking "UPDATE".

**Comment by aestivo** [comment]
I deleted and reinstalled the extension and found my last object! ;) I think everything is OK, I'm watching and little more tomorrow. Thank you very much for your quick correction.
