### ISSUE TITLE
Pb OPERA

### ISSUE THREAD

**Issue by LorenzoC007** [perceptron8/pinky.ext#45]
the plug-in shows half of the objects, no cask, no leather, no bags of cereals

**Comment by perceptron8** [comment]
https://addons.opera.com/en/extensions/details/pinky/?reports#r143818-thread

> Thanks for feedback! It's been fixed. I'm still waiting for Opera Add-ons moderators to make a few clicks.
> 
> Pinky v0.3.0 was submitted and is awaiting moderation since Jun 9
> Pinky v0.4.0 was submitted and is awaiting moderation since Jun 12

**Comment by LorenzoC007** [comment]
ok, thanks for the quick reply

**Comment by perceptron8** [comment]
@LorenzoC007 Good news! :)
> Status has changed for Pinky
> Pinky v0.4.0 on Opera Current:
> Published.

**Comment by LorenzoC007** [comment]
I just saw that, thanks

**Comment by LorenzoC007** [comment]
pinky works at 100%

**Comment by perceptron8** [comment]
cool, thanks for info!
