### ISSUE TITLE
Anniversary Event

### ISSUE THREAD

**Issue by lubrde** [perceptron8/pinky.ext#48]
Hello,
the new anniversary event is now available on the test server.
New collectibles items have also been added: Candles and Cake Dough
Players up to and including level 50 will only receive cake dough and Players at level 51 and above will only receive candles. At event start my level on the test server was 49. So during the event I can only find Cake Dough.
In the network analysis of my browser I was able to locate the image file:
https://ubistatic-a.akamaihd.net/0018/prestaging/GFX_HASHED/building_lib/589ca2af5d39b45a8ee351f55985d113e9cac13d.png

For the file of candles a player above level 50 must help out.
If you have any further questions, feel free to contact me. :-)

Best regards
Lukas

**Comment by perceptron8** [comment]
Hi Lukas,

thanks for letting me know about new collectibles and thanks again for taking time and performing network analysis :)

I'll add missing collectibles very soon. Then I'm going to release new Pinky version. After that I'll ask you to test it if you like.

With best wishes
Michal

**Comment by perceptron8** [comment]
I found the second one https://ubistatic-a.akamaihd.net/0018/prestaging/GFX_HASHED/building_lib/64af56a292cf9dc1f77bbd9332119dd3b46e3a9f.png!

**Comment by perceptron8** [comment]
Changes added in https://github.com/perceptron8/pinky.ext/commit/5f034bc904bf7c9f25ac4eb1000daacb40cd9f4c. New Pinky version (0.4.1) has been submitted and is awaiting for moderation.

**Comment by perceptron8** [comment]
You can now test Pinky v0.4.1 for Chrome and Firefox. If you use Opera, you'll have to wait approximately 1-2 days, as every new release in their store must be reviewed by human.

**Comment by lubrde** [comment]
Thank you very much for the quick response and customization of Pinky.
I tested it on the test server and it all works fine.
Thanks for the support :)

**Comment by siebenkopf** [comment]
Just a note: the new extension still seems to be unavailable for Opera. There, the latest version is listed as v0.4.0. Do you have any estimation on how long the update might take? Do you have any ways in speeding up the manual process on the Opera side?

Thanks a lot for the nice tool :-)

**Comment by siebenkopf** [comment]
@perceptron8 Thanks for the tip. The workaround works flawlessly.
