### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by NASCAR73** [perceptron8/pinky.ext#50]
Like you to include the new birthday items?

**Comment by perceptron8** [comment]
You mean cakes and candles? See #48 please.
I guess you use Opera. Pinky v0.4.1 has been submitted long time ago but is is still waiting for review. See https://github.com/perceptron8/pinky.ext/issues/48#issuecomment-414391140

Meanwhile you can use https://addons.opera.com/pl/extensions/details/install-chrome-extensions/ to install Pinky directly from Chrome Web Store https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna.

**Comment by perceptron8** [comment]
> Status has changed for Pinky
> Pinky v0.4.1 on Opera Current:
> Published.
