### ISSUE TITLE
Test Server defeated Pinky 9-28-18

### ISSUE THREAD

**Issue by AlliNel** [perceptron8/pinky.ext#51]
Test server has defeated Pinky. It no longer works there, so I suspect that on the regular game servers Pinky  will no longer work either after an updated version maintenance.
https://www.tsotesting.com/en/homepage

**Comment by perceptron8** [comment]
Works for me...?

**Comment by perceptron8** [comment]
Ok, good to know. Thanks!

**Comment by Kebabtomte** [comment]
Test server has beaten Pinky it seems since on live pinky works but now on test since last update pinky dont work.

**Comment by perceptron8** [comment]
@Kebabtomte Pinky v0.4.5 was submitted. Awaiting moderation.
