### ISSUE TITLE
Pinky not downloading from Firefox's Add-ons Manager

### ISSUE THREAD

**Issue by SkartakhDK** [perceptron8/pinky.ext#54]
When trying to install the Pinky add-on in Firefox, it says "Download failed."
I can install other add-ons (also Babel), so there is no problem with internet connectivity.

Tried to install the add-on from here: https://addons.mozilla.org/en-US/firefox/addon/_pinky/?src=search
Perhaps the "+ Add to Firefox" download link is broken?

**Comment by perceptron8** [comment]
It may be related to https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047.

**Comment by perceptron8** [comment]
https://twitter.com/firefox/status/1124527050490933248
As you can see, it's global problem.

**Comment by SkartakhDK** [comment]
OK thanks. The weird thing is that I can install other add-ons. But I'll wait and see if the hotfix removes the problem.

**Comment by SkartakhDK** [comment]
Good news - after manually forcing the hotfix, the addon installed and works.

**Comment by perceptron8** [comment]
That's great :-) Thanks for letting me know!
