### ISSUE TITLE
new update 2019/07 changed some tiles

### ISSUE THREAD

**Issue by djtfmineijizm** [perceptron8/pinky.ext#55]
the new optimized load times update changes some urls:
eg. Leather: https://ubistatic-a.akamaihd.net/0018/prestaging/GFX_HASHED/building_lib/c46291560daf1224ea94cb37c9489fffed9008e1.png

**Comment by perceptron8** [comment]
@djtfmineijizm Thanks for the info! Please let me know if anything changes again.

**Comment by perceptron8** [comment]
@djtfmineijizm v0.4.2 is coming soon.
