### ISSUE TITLE
Highlighting Collectables

### ISSUE THREAD

**Issue by BouncyTigger** [perceptron8/pinky.ext#69]
when highlighting collectables on someones island i can only highlight 2 items then it stops showing the collectables

**Comment by perceptron8** [comment]
But are they still pink?

**Comment by BouncyTigger** [comment]
yes just can't highlight them on other islands to help out is that a game
or pinky issue?

**Comment by perceptron8** [comment]
Some time ago I was able to reproduces this bug with no Pinky installed. It seems to be a game issue.
See #34.
