### ISSUE TITLE
Greetings, I'd like ton contact you.

### ISSUE THREAD

**Issue by Philippe-Alexandrian** [perceptron8/pinky.ext#70]
First of all, thanks for your clever job.

This gave me the idea to check available offers from the game (WS GetAvailableOffers).

Using firefox debug, I got an HTTP response from the HTTP request (send by the game) but I don't know how to decode it.
Do you have any idea that can help ?

[WS_GetAvailableOffers_Request_Header.txt](https://github.com/perceptron8/pinky.ext/files/4640905/WS_GetAvailableOffers_Request_Header.txt)
[WS_GetAvailableOffers_Request_Parameters.txt](https://github.com/perceptron8/pinky.ext/files/4640906/WS_GetAvailableOffers_Request_Parameters.txt)
[WS_GetAvailableOffers_Response_Header.txt](https://github.com/perceptron8/pinky.ext/files/4640907/WS_GetAvailableOffers_Response_Header.txt)
[WS_GetAvailableOffers_Response_Content.txt](https://github.com/perceptron8/pinky.ext/files/4640908/WS_GetAvailableOffers_Response_Content.txt)

PS: Sorry for using issue to contact you, but i didn't find any other way.

**Comment by perceptron8** [comment]
Hi!

First, you can experiment with Charles (https://www.charlesproxy.com/). It parses the binary AMF format so you can inspect requests and responses. Obiously you'll need to configure Firefox to use Charles as a proxy.

If you are familiar with nodejs or programming in general, you may like to take a look at https://github.com/perceptron8/amf (but you're on your own!). If you're more into Java, I recommend https://github.com/graniteds/graniteds.

Finally, you may find useful to read AFM 3 spec: https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/amf-file-format-spec.pdf.

Good luck!

**Comment by Philippe-Alexandrian** [comment]
Excellent !!!

I'm more a Java backend developper.
But I'm curious: I'll have a look to these web pages.

Thank you so much.



----- Mail original -----
De: "Michał Sobkiewicz" <notifications@github.com>
À: "perceptron8/pinky.ext" <pinky.ext@noreply.github.com>
Cc: "Philippe-Alexandrian" <bruno.lochet31@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 18 Mai 2020 00:13:17
Objet: Re: [perceptron8/pinky.ext] Greetings, I'd like ton contact you. (#70)





Hi! 

First, you can experiment with Charles ( https://www.charlesproxy.com/ ). It parses the binary AMF format so you can inspect requests and responses. Obiously you'll need to configure Firefox to use Charles as a proxy. 

If you are familiar with nodejs or programming in general, you may like to take a look at https://github.com/perceptron8/amf (but you're on your own!). If you're more into Java, I recommend https://github.com/graniteds/graniteds . 

Finally, you may find useful to read AFM 3 spec: https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/amf-file-format-spec.pdf . 

Good luck!

**Comment by perceptron8** [comment]
> I'm more a Java backend developper.

In that case, I think I can help you a little bit more. I'm a Java dev too. I won't spoil your fun, but I may give you some clues. Here they are.

Take a look at:
- org.eclipse.jetty:jetty-proxy
- org.eclipse.jetty:jetty-servlet
- org.graniteds:granite-client-java

Pay special attention to the following classes:
- AsyncMiddleManServlet
- AMF0MessagingCodec

With a little effort, you will be able to not only intercept AMF, but also modify requests on the fly.

I can't make my work public for legal reasons, hope you understand.

**Comment by dev151** [comment]
Hello Michal,

Thank you for your great job on this piece of software!
Philippe pointed that there is no other means to contact you so I woluld like to ask you for private conversation.
I'm also Java dev and concerned about "legal reasons".
Could you please contact me on my email: j.parasinski [at] mixbox dot pl?
Preferred language: Polish :)

Best regards.
