### ISSUE TITLE
End of flash -> slim

### ISSUE THREAD

**Issue by majkimajki** [perceptron8/pinky.ext#71]
Any idea if it is possible to add pinky to the slim browser?

**Comment by perceptron8** [comment]
I don't think it is or will be possible. There's no support for [webRequest](https://developer.chrome.com/extensions/webRequest) API. There's also no support for [declarativeNetRequest](https://developer.chrome.com/extensions/declarativeNetRequest) API, which could be used as a fallback.

See https://docs.nwjs.io/en/latest/References/Chrome%20Extension%20APIs/ if you like.

**Comment by criss20ster** [comment]
Hi. I have a question. How now you can operate this overlay to find collectibles in the game

**Comment by perceptron8** [comment]
@criss20ster Hi. You can't. Pinky requires web extensions (webRequest API in particular) to be available to use in the client.

**Comment by perceptron8** [comment]
It's very likely that Unity version will soon be supported. See #74.
