### ISSUE TITLE
Finding picture hashed name

### ISSUE THREAD

**Issue by pryszkowski** [perceptron8/pinky.ext#73]
Question: How did you find hashed names of the files with pictures of collectibles?
I would like to extend mapping like this
`"3d22e289f157476f3a79a53c1ce2d16b29064c8a.png", // buffad_collectible_bridge_base_material.png`
with some other elements.

**Comment by perceptron8** [comment]
If you want to just extend mapping, you don't need filenames. Simply add more resources to list (BTW they are not hashed names, but hashed content). If you really want to get names, you may need to inspect swf.
