### ISSUE TITLE
Unity version on the test server tsotesting2.com

### ISSUE THREAD

**Issue by janrenzlow** [perceptron8/pinky.ext#74]
DE Unity-Version auf dem Testserver tsotesting2.com

Hallo Michal,
die UNITY-Version ist seit Dienstag auf dem zweiten Testserver https://www.tsotesting2.com/en/play. Das Spiel hat noch viele Bugs https://forum.diesiedleronline.de/threads/143049-BUG-REPORT-Bekannte-Probleme-Unity. Der Bilderspeicher %localappdata%\Microsoft\Windows\INetCache\IE existiert nicht mehr. Jeder Spieler muss bei Level 0 anfangen. Das ist recht mühsam. Das Sammeln der Items beginnt erst ab Level 16. Mein Name in tsotesting2 ist "xxxxx". Wenn Du mich um Freundschaft fragen, dann kannst Du meine Insel verwenden um Pinky zu testen. 
**Wird es eine Chance geben, Pinky in die UNITY-Version zu portieren?**
Auf Deine Antwort bin ich gespannt
Jan

EN:Unity version on the test server

Hello Michal,
the UNITY version has been on the second test server https://www.tsotesting2.com/en/play since Tuesday. The game still has a lot of bugs https://forum.diesiedleronline.de/threads/143049-BUG-REPORT-Bekante-Probleme-Unity. The cache for images %localappdata% \ Microsoft \ Windows \ INetCache \ IE no longer exists. Every player has to start at level 0. It is quite tedious. Collecting the items only starts at level 16. My name in tsotesting2 is "xxxxx". If you ask me for friendship, then you can use my island to test Pinky. 
**Will there be a chance to port Pinky to the UNITY version?**
I am looking forward to your answer
Jan

PL:Witaj Michał,
wersja UNITY znajduje się na drugim serwerze testowym https://www.tsotesting2.com/en/play od wtorku. Gra wciąż ma wiele błędów https://forum.diesiedleronline.de/threads/143049-BUG-REPORT-Bekante-Probleme-Unity. Pamięć obrazu% localappdata% \ Microsoft \ Windows \ INetCache \ IE już nie istnieje. Każdy gracz musi zacząć na poziomie 0. To dość uciążliwe. Zbieranie przedmiotów zaczyna się dopiero na poziomie 16. Nazywam się w tsotesting2 "xxxx". Jeśli zapytasz mnie o przyjaźń, możesz użyć mojej wyspy do przetestowania Pinky'ego. 
**Czy będzie szansa na przeniesienie Pinky'ego do wersji UNITY?**
czekam na Twoją odpowiedź
Jan

**Comment by perceptron8** [comment]
Hello Jan,

Thanks for letting me know.
There is a chance and I'll do my best to update Pinky.
It's possible that one day I'll ask you for friendship.

Michał

**Comment by n3rdc0r3** [comment]
I edited the extension and imported it as an unpacked version into Brave - only two small changes are necessary to make Pinky work again on the new test server:

background.js
`+ "https://ubistatic-a.akamaihd.net/0018/staging/GFX_HASHED/building_lib/",`

manifest.json
`+ "https://www.tsotesting2.com/",`

![brave_euI5EWFZJ0](https://user-images.githubusercontent.com/62601870/116766120-16eddb00-aa29-11eb-872d-21a55f15bbbc.png)

**Comment by perceptron8** [comment]
Good news! I was able to verify that no additional changes are necessary, i.e. there is no need to update `collectibles'. I'll try to publish new version today.

**Comment by perceptron8** [comment]
New version has been sent for review. It may take some time.

**Comment by perceptron8** [comment]
Pinky v0.5.0 has landed.
