### ISSUE TITLE
Allow toggling on/off

### ISSUE THREAD

**Issue by wizofaus** [perceptron8/pinky.ext#76]
Great extension, but I don't really want my collectibles to ALWAYS be bright pink squares - having the option to just have it briefly reveal the locations on demand would be great.  Could potentially do myself but I haven't really done much in the way of chrome extension development (did play around with it a while back briefly).  But it would mean having an option to not show the pink squares normally and then a command to activate them...
And yeah, I understand the way it works this would be somewhat hard to do, but not impossible I'd think...maybe it would require reloading the game page though.

**Comment by perceptron8** [comment]
As you understand, toggling is impossible as Pinky is based on asset substitution, not image processing. Temporarily enabling / disabling extension (settings -> manage extensions) and reloading game page is an option, albeit a time consuming one.

**Comment by perceptron8** [comment]
Fetching, processing and redirecting to processed images (fetch -> canvas -> blob url) should be possible now (wasn't some time ago, see https://github.com/perceptron8/pinky.ext/issues/1#issuecomment-109580243), but it's not something I'd like to do in the nearest future. I think that not-so-suble magenta replacement does the job well enough - after all, the point is that the collectibles should be as easy to find as possible.
