### ISSUE TITLE
Link erróneo

### ISSUE THREAD

**Issue by Hunter-Atenea** [perceptron8/pinky.ext#77]
hola!

Pinky sirve en todos los servidores de TSO, menos en LATAM, porque esta mal escrito, lo correcto seria así: 

https://www.juego-thesettlersonline.com/es/página-de-inicio

Los usuarios de latan estaremos muy agradecidos de que sea modificado el código y podamos usar la aplicación.

Saludos cordiales.

**Comment by perceptron8** [comment]
Hi! Thank you for taking the time to report this issue. The version containing the fix (0.6.0) will be released later today.
